-- 단어 설명용 그래프·표 (words.visuals). 형식은 src/types.ts의 WordVisual 참고.
-- ecos 항목은 ecos-series 함수(ECOS_API_KEY 필요)가 한국은행 통계를 불러온다. 개념 그래프 수치는 설명용 예시.
-- 재실행해도 같은 값으로 덮어쓴다.

ALTER TABLE public.words ADD COLUMN IF NOT EXISTS visuals JSONB;

UPDATE public.words SET visuals = '[{"type":"line","title":"100만 원을 연 10%로 10년 맡기면","unit":"만 원","x":["0년","1년","2년","3년","4년","5년","6년","7년","8년","9년","10년"],"series":[{"name":"복리","values":[100.0,110.0,121.0,133.1,146.4,161.1,177.2,194.9,214.4,235.8,259.4]},{"name":"단리","values":[100,110,120,130,140,150,160,170,180,190,200]}],"caption":"단리: 처음 넣은 100만 원에만 이자가 붙어요.\n1년 +10만 → 2년 +10만 → 3년 +10만\n\n복리: 통장에 있는 돈 전체에 이자가 붙어요.\n1년 +10만 → 2년 +11만 → 3년 +12.1만\n작년 이자도 올해 이자를 만들어요.\n\n10년째 한 해 이자는 단리 10만 원, 복리 23.6만 원이에요.\n(세금·수수료 제외 예시)"},{"type":"table","title":"단리와 복리 비교","columns":["구분","단리","복리"],"rows":[["이자가 붙는 곳","원금에만","원금 + 쌓인 이자"],["10년 뒤 (100만 원, 연 10%)","200만 원","약 259만 원"],["시간이 지날수록","일정하게 증가","점점 빠르게 증가"]]}]'::jsonb WHERE id = 724 AND word = '복리';
UPDATE public.words SET visuals = '[{"type":"line","title":"100만 원을 연 10%로 10년 맡기면","unit":"만 원","x":["0년","1년","2년","3년","4년","5년","6년","7년","8년","9년","10년"],"series":[{"name":"복리","values":[100.0,110.0,121.0,133.1,146.4,161.1,177.2,194.9,214.4,235.8,259.4]},{"name":"단리","values":[100,110,120,130,140,150,160,170,180,190,200]}],"caption":"단리: 처음 넣은 100만 원에만 이자가 붙어요.\n1년 +10만 → 2년 +10만 → 3년 +10만\n\n복리: 통장에 있는 돈 전체에 이자가 붙어요.\n1년 +10만 → 2년 +11만 → 3년 +12.1만\n작년 이자도 올해 이자를 만들어요.\n\n10년째 한 해 이자는 단리 10만 원, 복리 23.6만 원이에요.\n(세금·수수료 제외 예시)"},{"type":"table","title":"단리와 복리 비교","columns":["구분","단리","복리"],"rows":[["이자가 붙는 곳","원금에만","원금 + 쌓인 이자"],["10년 뒤 (100만 원, 연 10%)","200만 원","약 259만 원"],["시간이 지날수록","일정하게 증가","점점 빠르게 증가"]]}]'::jsonb WHERE id = 167 AND word = '단리';
UPDATE public.words SET visuals = '[{"type":"line","title":"피자를 한 조각씩 더 먹을 때 만족도 (예시)","unit":"점","x":["1조각","2조각","3조각","4조각","5조각","6조각"],"series":[{"name":"한 조각 더 먹을 때 느는 만족(한계효용)","values":[10,8,6,4,2,0]},{"name":"전체 만족(총효용)","values":[10,18,24,28,30,30]}],"caption":"조각이 늘수록 한 조각이 주는 추가 만족은 줄어들어요. 한계효용이 0이 되면 더 먹어도 전체 만족이 늘지 않아요."}]'::jsonb WHERE id = 645 AND word = '한계효용';
UPDATE public.words SET visuals = '[{"type":"line","title":"같은 밭에 일꾼을 한 명씩 더 넣을 때 수확량 (예시)","unit":"kg","x":["1명","2명","3명","4명","5명","6명"],"series":[{"name":"한 명 더 넣을 때 느는 수확","values":[10,15,11,7,4,2]},{"name":"전체 수확","values":[10,25,36,43,47,49]}],"caption":"땅(고정된 생산요소)은 그대로인데 일꾼만 늘리면, 어느 순간부터 한 명이 더해 주는 수확이 점점 줄어요."}]'::jsonb WHERE id = 324 AND word = '수확체감의 법칙';
UPDATE public.words SET visuals = '[{"type":"ecos","title":"한국은행 기준금리 최근 5년","stat":"722Y001","item":"0101000","cycle":"M","unit":"%","months":60,"caption":"기준금리가 오르면 대출·예금 금리도 따라 오르는 경향이 있어요."}]'::jsonb WHERE id = 142 AND word = '기준금리';
UPDATE public.words SET visuals = '[{"type":"ecos","title":"소비자물가지수 최근 5년 (2020년 = 100)","stat":"901Y009","item":"0","cycle":"M","unit":"","months":60,"caption":"지수가 오를수록 같은 돈으로 살 수 있는 물건이 줄어요. 2020년 물가를 100으로 봤을 때의 값이에요."},{"type":"table","title":"인플레이션 · 디플레이션 · 스태그플레이션","columns":["구분","물가","경기"],"rows":[["인플레이션","계속 오름","대체로 호황과 함께"],["디플레이션","계속 내림","대체로 불황과 함께"],["스태그플레이션","오름","침체"]]}]'::jsonb WHERE id = 454 AND word = '인플레이션';
UPDATE public.words SET visuals = '[{"type":"ecos","title":"소비자물가지수 최근 5년 (2020년 = 100)","stat":"901Y009","item":"0","cycle":"M","unit":"","months":60,"caption":"지수가 오를수록 같은 돈으로 살 수 있는 물건이 줄어요. 2020년 물가를 100으로 봤을 때의 값이에요."}]'::jsonb WHERE id = 310 AND word = '소비자물가지수(CPI)';
UPDATE public.words SET visuals = '[{"type":"ecos","title":"소비자물가지수 최근 5년 (2020년 = 100)","stat":"901Y009","item":"0","cycle":"M","unit":"","months":60,"caption":"지수가 오를수록 같은 돈으로 살 수 있는 물건이 줄어요. 2020년 물가를 100으로 봤을 때의 값이에요."}]'::jsonb WHERE id = 219 AND word = '물가지수';
UPDATE public.words SET visuals = '[{"type":"table","title":"인플레이션 · 디플레이션 · 스태그플레이션","columns":["구분","물가","경기"],"rows":[["인플레이션","계속 오름","대체로 호황과 함께"],["디플레이션","계속 내림","대체로 불황과 함께"],["스태그플레이션","오름","침체"]]}]'::jsonb WHERE id = 191 AND word = '디플레이션';
UPDATE public.words SET visuals = '[{"type":"table","title":"인플레이션 · 디플레이션 · 스태그플레이션","columns":["구분","물가","경기"],"rows":[["인플레이션","계속 오름","대체로 호황과 함께"],["디플레이션","계속 내림","대체로 불황과 함께"],["스태그플레이션","오름","침체"]]}]'::jsonb WHERE id = 334 AND word = '스태그플레이션';
UPDATE public.words SET visuals = '[{"type":"ecos","title":"원/달러 환율 최근 5년 (월평균)","stat":"731Y004","item":"0000001/0000100","cycle":"M","unit":"원","months":60,"caption":"숫자가 클수록 1달러를 사는 데 원화가 더 많이 들어요(원화 가치 하락)."}]'::jsonb WHERE id = 144 AND word = '기준환율';
UPDATE public.words SET visuals = '[{"type":"table","title":"보완재와 대체재","columns":["구분","보완재","대체재"],"rows":[["뜻","함께 쓸 때 만족이 커지는 재화","서로 대신 쓸 수 있는 재화"],["예시","커피와 설탕, 프린터와 잉크","버터와 마가린, 콜라와 사이다"],["한쪽 가격이 오르면","다른 쪽 수요 감소","다른 쪽 수요 증가"]]}]'::jsonb WHERE id = 241 AND word = '보완재';
UPDATE public.words SET visuals = '[{"type":"table","title":"탄력적 vs 비탄력적 수요","columns":["구분","탄력적 (1보다 큼)","비탄력적 (1보다 작음)"],"rows":[["가격이 10% 오르면","수요가 10%보다 많이 줄어요","수요가 10%보다 적게 줄어요"],["어떤 물건","대신할 게 많은 물건, 사치품","쌀·전기 같은 생활 필수품"]]}]'::jsonb WHERE id = 317 AND word = '수요탄력성';

NOTIFY pgrst, 'reload schema';

-- 확인: 13행이 나와야 한다
-- SELECT id, word, jsonb_array_length(visuals) FROM public.words WHERE visuals IS NOT NULL ORDER BY id;
