-- ===== 콘텐츠 정제 1/36 (refine.py 생성 — 손으로 고치지 말고 meanings.py를 고친 뒤 다시 실행) =====
-- 뜻 전면 재작성·슬래시 항목 분리(신규 31행)·힌트 기본형 초성·related_words 정리·본문 줄이음 자국 제거.
-- 적용 순서: 16_words_refine_1..N -> 17_courses.sql

INSERT INTO public.words (id, word, meaning, detailed_meaning, news_example, hint, related_words) VALUES
(717,'직접금융','주식·채권을 발행해 금융회사 없이 시장에서 직접 자금을 모으는 방식','자금 잉여주체와 자금 부족주체 사이에 은행이나 저축은행 신용협동기구 등 금융기관이 개입하여 자금을 중개하는 방식을 간접금융(Indirect Financing)이라고 한다. 즉 금융기관이 일반 대중으로부터 예금을 받아 기업 등 다른 경제주체에게 대출해 주는 방식이다. 한편 주식, 채권 발행의 경우와 같이 자금수요자가 금융기관을 통하지 않고 금융시장에서 직접 필요자금을 조달하는 방식을 직접금융(Direct Financing)이라고 한다. 간접금융에 서는 은행이 중추적인 기능을 하고, 직접금융에서는 주식과 채권이 거래되는 자본시장이 중요한 역할을 수행한다. 직접금융과 간접금융은 상호 경쟁적일 뿐만 아니라 보완적이기도 하므로 균형적으로 발전될 필요가 있다. 직접금융과 간접금융의 상대적 비중이 어느정도이어야 이상적인지는 해당 국가의 경제발전 단계나 경제구조에 따라 달라질 수밖에 없다. 예를 들면 중소기업의 비중이 높은 국가일수록 정보의 비대칭성 문제를 완화하기위해 간접금융이 더 중요하고, 혁신산업에 의해 주도되는 경제일수록 미래의 성장 가능성을 보고 투자하고 그 위험과 이익을 공유하는 주식 등 직접금융의 역할이 더 중요할 것이다. 일반적으로 금융시장이 발달함에 따라 직접금융 비중이 높아진다.','','ㅈㅈㄱㅇ',ARRAY['금융제도','장기금융시장(자본시장)','간접금융']::text[]),
(718,'직접세','소득세처럼 내 소득이나 재산에 직접 매겨 내가 내는 세금','조세는 납세의무자와 실제로 세금을 부담하게 되는 조세부담자가 일치하는지 여부에 따라 간접세(Indirect Tax)와 직접세(Direct Tax)로 구분된다. 납세의무자와 조세부담자가 일치하여 조세부담이 전가(轉嫁)되지 않는 조세를 직접세라고 하며, 대표적인 예로는 소득세, 법인세, 상속세, 증여세, 종합부동산세 등이 있다. 이와 달리 납세의무자와 조세부담자가 일치하지 않고 조세의 부담이 타인에게 전가되는 세금을 간접세라고 하며, 대표적인 예로는 부가가치세, 개별소비세, 주세, 인지세, 증권거래세 등이 있다. 간접세는 조세에 대한 저항이 적고 징수가 간편하여 조세수입의 확보가 용이하다는 장점이 있다. 반면, 개인의 사정을 고려할 수 없으므로 누진세율(累進稅率)을 적용하지 못하고 비례세율이 적용됨으로써 소득이 적은 자에게 상대적으로 높은 조세부담률이 적용되는 역진성(逆進性) 을 띠게 되어 공평부담의 원칙에 어긋난다는 단점이 있다. 한편, 국민계정체계에서는 조세의 실질적인 부담주체를 결정하기가 쉽지 않은 점 등을 감안하여 간접세와 직접세 대신생산 및 수입세, 소득 및 부 등에 대한 경상세, 자본세란 용어를 사용하고 있다.','','ㅈㅈㅅ',ARRAY['간접세']::text[]),
(719,'전업주의','은행·증권·보험이 각자 고유 업무만 하도록 나누는 방식','하나의 금융회사가 제공할 수 있는 금융서비스의 종류를 어떻게 정하느냐에 따라 겸업주의(Universal banking)와 전업주의(Specialized banking)로 구분된다. 겸업주의는 한 금융회사가 은행·증권·보험 등 여러 금융서비스를 취급할 수 있는 반면 전업주의는 은행· 증권사·보험사 등이 각각 해당하는 고유의 서비스만을 제공하는 방식이다. 현재 세계적으로 겸업주의가 대세를 이루고 있으나 국가별로는 법적 형태면에서 차이가 있다. 독일, 네덜란드, 스위스 등 대부분의 유럽국가는 은행산업과 증권산업 간에 아무런 장벽을 두지 않고 하나의 은행이라는 법적 조직체 안에서 은행, 증권, 보험 등의 모든 서비스를 제공하는 내부겸업 시스템을 근간으로 한다. 반면에 영국 및 영연방국가, 현재의 미국에서는 은행이 자회사를 통해 증권이나 보험업무를 수행하는 외부겸업 시스템을 택하고 있다. 전업주의는 종전의 일본 및 미국의 경우처럼 은행산업과 여타 금융서비스 산업의 법적인분리를 특징으로 한다. 우리나라는 과거에 전업주의를 채택하였으나 1980년대 이후 내부겸업을 확대하여 왔으며 2000년 「금융지주회사법」 제정으로 미국, 일본 등과 같은 외부겸업 시스템을 도입하였다. 한편 국외에서는 2008년 글로벌 금융위기의 원인 중 하나로 금융회사의 과도한 금융겸업 확대가 지목되면서 이를 우려하는 목소리가 커지고 있다. 그결과 미국은 은행부문의 헤지펀드 및 사모펀드 운영을 제한하는 볼커룰(Volcker Rule)을 도입하였으며, 영국은 예금·대출 위주의 소매은행으로부터 리스크가 높은 증권투자업무를 분리하는 ‘소매은행업 격리제도(ring-fenced bank)’를 마련하였다.','','ㅈㅇㅈㅇ',ARRAY['볼커룰','겸업주의']::text[]),
(720,'비경제활동인구','15세 이상이지만 일할 의사나 능력이 없어 노동시장 밖에 있는 사람','만15세 이상 인구 중 일할 수 있는 능력과 취업의사를 동시에 갖춘 사람을 경제활동인구라 한다. 경제활동인구는 현재 취업상태에 있는지에 따라 취업자와 실업자로 구분된다. 취업자란 매월 15일이 포함된 1주일 동안에 수입을 목적으로 1시간 이상 일한 사람과 본인 또는 가족이 운영하는 농장이나 사업체에서 주당 18시간 이상 일한 무급가족종사자를 가리킨다. 그밖에 일정한 직장이나 사업장은 가지고 있으나 일시적인 질병, 일기불순, 휴가, 노동쟁의 등의 사유로 조사기간에 일을 하지 않은 사람도 취업자로 분류된다. 실업자란 적극적으로 일자리를 구해보았으나 일을 하지 못한 사람으로서 즉시 취업이 가능한 사람을 말한다. 한편 15세 이상 인구 중 경제활동인구에 포함되지 않은 사람, 즉 조사대상기간에 취업도 실업도 아닌 상태에 있는 사람은 비경제활동인구로 분류된다. 비경제활동인구에는 집안에서 가사와 육아를 도맡아 하는 전업주부, 학교에 다니는 학생, 일을 할 수없는 연로자와 심신장애자, 구직단념자 등이 포함된다. 경제활동참가율은 15세 이상 인구에 대한 경제활동인구의 비율을 말한다. 경제활동인구(취업자 + 실업자) 경제활동참가율 = ×100 15세 이상 인구','','ㅂㄱㅈㅎㄷㅇㄱ',ARRAY['고용보조지표','잠재경제활동인구','경제활동인구','경제활동참가율']::text[]),
(721,'경제활동참가율','15세 이상 인구 중 일하거나 일자리를 찾는 사람의 비율','만15세 이상 인구 중 일할 수 있는 능력과 취업의사를 동시에 갖춘 사람을 경제활동인구라 한다. 경제활동인구는 현재 취업상태에 있는지에 따라 취업자와 실업자로 구분된다. 취업자란 매월 15일이 포함된 1주일 동안에 수입을 목적으로 1시간 이상 일한 사람과 본인 또는 가족이 운영하는 농장이나 사업체에서 주당 18시간 이상 일한 무급가족종사자를 가리킨다. 그밖에 일정한 직장이나 사업장은 가지고 있으나 일시적인 질병, 일기불순, 휴가, 노동쟁의 등의 사유로 조사기간에 일을 하지 않은 사람도 취업자로 분류된다. 실업자란 적극적으로 일자리를 구해보았으나 일을 하지 못한 사람으로서 즉시 취업이 가능한 사람을 말한다. 한편 15세 이상 인구 중 경제활동인구에 포함되지 않은 사람, 즉 조사대상기간에 취업도 실업도 아닌 상태에 있는 사람은 비경제활동인구로 분류된다. 비경제활동인구에는 집안에서 가사와 육아를 도맡아 하는 전업주부, 학교에 다니는 학생, 일을 할 수없는 연로자와 심신장애자, 구직단념자 등이 포함된다. 경제활동참가율은 15세 이상 인구에 대한 경제활동인구의 비율을 말한다. 경제활동인구(취업자 + 실업자) 경제활동참가율 = ×100 15세 이상 인구','','ㄱㅈㅎㄷㅊㄱㅇ',ARRAY['고용보조지표','잠재경제활동인구','경제활동인구','비경제활동인구']::text[]),
(722,'자유변동환율제도','외환의 수요와 공급에 따라 환율이 시장에서 자유롭게 정해지는 제도','환율제도는 고정환율제도(Fixed Exchange Rate System)와 자유변동환율제도(Free Floating Exchange Rate System)를 양극단으로 하여 이를 절충하는 다양한 형태로 분류될 수 있다. 고정환율제도는 환율을 정부나 중앙은행이 적정하다고 판단하는 수준으로 일정하게 유지하는 제도이다. 반면 자유변동환율제도는 환율이 외환의 수요와 공급에 의 해 자율적으로 결정되도록 하는 환율제도를 말한다. 고정환율제도는 환율 변동에 따른 충격을 완화하고 거시경제정책의 자율성을 어느 정도 확보할 수 있다는 장점이 있으나 이 를 위해서는 자본이동의 제약이 불가피하여 결과적으로 외화유동성이 부족해질 가능성이 있다. 이 경우 대외불균형이 지속되거나 기초경제여건이 악화되면 환투기공격에 쉽게노출되는 단점이 있다. 반면 자유변동환율제도에서는 자본이동이 자유롭게 이루어지므로 외화유동성 확보가 용이하고 외부충격이 환율 변동에 의해 흡수됨으로써 거시경제정책의 자율적 수행이 수월한 장점이 있다. 다만 외환시장 규모가 작고 외부충격의 흡수 능력이 부족한 신흥국은 환율 변동성의 확대가 경제의 교란 요인으로 작용할 가능성이 크다. 한편 어떤 환율제도를 채택하더라도 ① 통화정책의 자율성 ② 자유로운 자본이동 ③ 환율 안정 등 세 가지 정책목표를 동시에 달성하기는 현실적으로 어려운데, 이를 삼불원칙 (impossible trinity 또는 trilemma)이라고 한다.','','ㅈㅇㅂㄷㅎㅇㅈㄷ',ARRAY['삼불원칙','외환시장','고정환율제도']::text[]),
(723,'국민총처분가능소득(GNDI)','감가상각을 빼기 전, 나라 전체가 쓸 수 있는 소득의 총액','국민처분가능소득(NDI; National Disposable Income)은 나라 경제 전체가 소비나 저축으로 자유로이 처분할 수 있는 소득으로서 거주자와 비거주자 간의 소득이전이 반영된 것이다. 국민처분가능소득은 국민순소득(NNI; Net National Income)에 교포송금 등과 같이 생산활동과는 관계없이 외국으로부터 받은 소득(국외수취경상이전)을 더하고 무상원조 등 외국에 지급한 소득(국외지급경상이전)을 차감하여 산출한다. 한편 국민처분가능소득에 고정자본소모를 더한 것을 국민총처분가능소득(GNDI; Gross National Disposable Income)이라고 하는데 소비와 저축을 국민총처분가능소득으로 나누어 구한 값을 각각 평균소비성향, 평균저축성향이라고 한다. 국민총처분가능소득은 총저축률과 총투자율을 산출하는데도 이용된다. 국민처분가능소득(NDI) = 국민순소득* + 국외순수취경상이전** * 국외순수취 영업이익 및 재산소득이 반영된 피용자보수 및 영업이익 + 순생산 및 수입세 ** ‌교포송금 등과 같이 생산활동과는 관계없이 외국으로부터 받은 소득(국외수취경상이전)에서 무상원조 등으로 외국에 지급한 소득(국외지급경상이전)을 뺀 금액국민총처분가능소득(GNDI) = 국민처분가능소득 + 고정자본소모 = 최종소비지출 + 총저축','','ㄱㅁㅊㅊㅂㄱㄴㅅㄷ',ARRAY['국민총소득(GNI)','국민처분가능소득(NDI)']::text[]),
(724,'복리','이자에도 다시 이자가 붙어 눈덩이처럼 불어나는 방식','단리(Simple Interest)는 원금에 대해서만 약정된 이율과 기간을 곱하여 이자를 산출하는 방식이다. 예를 들어 1억원을 만기 2년, 연 3%에 단리로 정기예금을 하는 경우 2년후원리금은 106백만원[100백만원(1+3%×2)]이다. 이때 실효수익률은 연 3%(6%/2)로 표면금리와 동일하다. 반면 복리(Compound Interest)는 일정 기간마다 발생한 이자를 원금에 합산한 후 그 합산금액에 대한 이자를 다시 계산하는 방식이다. 예를 들어 1억원을 만기 2년, 연 3%에 6개월 복리(6개월마다 이자를 원금에 가산)로 정기예금을 하는 경우 2년후 원리금은 106.14백만원[100백만원(1+3%/2)^4]이다. 이 경우 실효수익률은 연 3.07%(6.14%/2)이다. 위 예에서는 복리로 예금했을 때 단리보다 14만원의 이자를 더 받게 된다. 복리효과는 간단히 말해 이자가 이자를 낳는 원리이기 때문에 시간이 지날수록추가되는 이자부분이 커지면서 전체 저축 원리금이 기하급수적으로 늘어나는 원리이다. 따라서 저축기간이 짧으면 복리효과가 크지 않은 반면 저축기간이 길면 길수록 약간의 금리 차이(복리가 단리보다 높으므로)에도 이자금액이 크게 벌어지게 된다. 복리에서는 72 법칙이라는 것이 있다. 이자가 복리로 붙을 경우 원리금이 커지기 때문에 원리금이 두 배 (100%)로 불어나는데 필요한 저축기간과 수익률의 곱이 100%가 아니라 72%만 되면 된 다는 것이다. 위 예에서 보면 1억원을 2억원으로 불리는데 걸리는 기간은 단리의 경우 약 33년(100백만원/3백만원)이 소요되는 반면 복리의 경우 24년(72%/3%)이 소요되어 1억원을 2억원으로 불리는데 걸리는 기간이 복리가 단리보다 9년이나 짧다. 우리가 꾸준한 저축을 강조하는 이유는 저축의 경제적 성과 뒤에는 복리효과가 숨어있기 때문이다.','','ㅂㄹ',ARRAY['단리']::text[]),
(725,'복수금리방식','입찰에서 각자 써낸 금리대로 따로따로 발행금리를 정하는 방식','경쟁입찰에 따른 발행금리 결정방식에는 복수금리(Conventional)방식과 단일금리 (Dutch)방식이 있다. 복수금리(가격)방식은 각 낙찰자가 입찰시 제시한 금리(가격)를 발행금리(발행가격)로 하는 방식이며, 단일금리(단일가격)방식은 각 낙찰자가 입찰시 제시한 금리(가격) 중 최고금리(최저가격)를 발행금리(발행가격)로 하는 방식이다. 유동성 흡수 시에는 금융기관의 자금운용을 제약한다는 점을 고려하여 금융기관에 유리하게 단일금리방식을 적용하는 반면 유동성 지원 시에는 금융기관의 입찰 독려를 위해 유인을 제공할 필요가 없으므로 복수금리결정방식을 적용하는 경향이 있다. 현재 통화안정증권 발행시 입찰시행 전에 발행금리 결정방식을 공고하고 있으며 입찰참가자에게 더욱 유리한 단일금리방식을 주로 사용한다. 그리고 공개시장운영 수단으로 환매조건부증권(RP) 매매를 경쟁입찰 방식으로 진행할 경우 RP매각 시에는 단일금리방식을, RP매입 시에는 복수금리방식을 주로 사용하고 있다.','','ㅂㅅㄱㄹㅂㅅ',ARRAY['통화안정증권','단일금리방식']::text[]),
(726,'익일결제','외환거래 계약 다음 영업일에 결제하는 방식','현물환거래의 결제는 거래당사자 상호 간에 신용위험을 회피하기 위하여 거래계약일과 같은 날짜에 결제가 이루어지는 것을 원칙으로 하고 있다. 그런데 외환거래의 경우 결제되는 은행의 소재 국가가 서로 다르고 각 국가의 영업일도 다를 수 있기 때문에 결제일의 조정이 필요하게 된다. 이에 따라 현물환거래는 계약을 체결한 시점과 인수·인도가 이 루어지는 시점이 다를 수 있으며, 결제 시점에 따라 다음 세 가지로 분류한다. 당일결제 (value today)는 거래계약일에 외환의 인수·인도와 관련 대금의 결제가 이루어지는 현물환 거래방식이다. 익영업일결제(value tomorrow)는 거래계약 후 1영업일에 결제가 이루어지고, 익익영업일결제(value spot)는 거래계약 후 2영업일에 결제가 이루어지는 거래방식이다. 한편 2영업일 경과 후 결제가 이루어지는 외환거래는 현물환거래가 아니라 선물환거래로 분류한다.','','ㅇㅇㄱㅈ',ARRAY['선물환거래','당일결제','익익일결제']::text[]),
(727,'익익일결제','외환거래 계약 이틀 뒤 영업일에 결제하는 방식(현물환의 기본)','현물환거래의 결제는 거래당사자 상호 간에 신용위험을 회피하기 위하여 거래계약일과 같은 날짜에 결제가 이루어지는 것을 원칙으로 하고 있다. 그런데 외환거래의 경우 결제되는 은행의 소재 국가가 서로 다르고 각 국가의 영업일도 다를 수 있기 때문에 결제일의 조정이 필요하게 된다. 이에 따라 현물환거래는 계약을 체결한 시점과 인수·인도가 이 루어지는 시점이 다를 수 있으며, 결제 시점에 따라 다음 세 가지로 분류한다. 당일결제 (value today)는 거래계약일에 외환의 인수·인도와 관련 대금의 결제가 이루어지는 현물환 거래방식이다. 익영업일결제(value tomorrow)는 거래계약 후 1영업일에 결제가 이루어지고, 익익영업일결제(value spot)는 거래계약 후 2영업일에 결제가 이루어지는 거래방식이다. 한편 2영업일 경과 후 결제가 이루어지는 외환거래는 현물환거래가 아니라 선물환거래로 분류한다.','','ㅇㅇㅇㄱㅈ',ARRAY['선물환거래','당일결제','익일결제']::text[]),
(728,'커플링','한 나라 경제나 자산이 세계 흐름과 같은 방향으로 움직이는 동조화 현상','디커플링(Decoupling)이란 탈동조화라고 번역할 수 있는데, 어떤 나라나 지역의 경제가 인접한 다른 국가나 전반적인 세계 경제의 흐름과는 다른 모습을 보이는 현상을 말한다. 디커플링의 예로는 금융위기 이후 신흥국가나 유로지역 국가 등이 미국 경제와 다른 모습을 보이는 것을 들 수 있다. 이외에도 주가나 금리, 환율 등 일부 경제 변수의 흐름이 국가 간 또는 특정 국가 내에서 서로 다른 흐름을 보이는 현상도 디커플링이라고 할 수 있다. 예를 들어 국가 간의 경우 미국의 주가와 한국의 주가가 다른 방향으로 움직이거나, 한 국가 내에서의 경우 주가가 하락함에도 해당국 통화가 강세 현상을 보이는 경우 등을 들 수있다. 반대로 한 나라 또는 지역의 경제가 인접한 다른 국가나 세계 경제 흐름과 유사한 흐름을 보이는 것을 커플링(동조화, Coupling)이라 한다.','','ㅋㅍㄹ',ARRAY['디커플링']::text[]),
(729,'리스크 오프(Risk Off)','투자자들이 채권·금 같은 안전자산으로 피하는 분위기','리스크 온(Risk On)과 리스크 오프(Risk Off)는 투자 심리를 나타내는 용어로서 시장의 위험 선호도와 위험 회피 심리를 반영한다. 리스크 온은 투자자들이 위험 자산(주식, 암호화폐 등)에 적극적으로 투자하는 상황을 의미하고, 리스크 오프는 반대로 안전 자산(채권, 금 등)으로 투자 자금을 이동하는 상황을 의미한다. 리스크 온 상황에서는 경제 성장 기대감 증대, 금리 인상 가능성 감소, 기업 실적 호조 등의 요인이 작용하는 가운데 투자자들이 경제 상황에 대해 낙관적인 태도를 보이며 위험 자산에 대한 투자를 늘리는 경향을 보인다. 반대로 리스크 오프 상황에서는 경기침체 우려 증대, 금리 인상 가능성 증가, 지정학적 리스크 고조 등의 요인이 작용하는 가운데 투자자들이 경제 상황에 대해 비관적인태도를 보이며 안전 자산으로 자금을 이동시키는 경향을 보인다.','','ㄹㅅㅋㅇㅍ',ARRAY['위험 선호/회피','안전자산/위험자산','리스크 온(Risk On)']::text[]),
(730,'환가료','은행이 외화를 먼저 원화로 내주고 실제 입금될 때까지 받는 이자 성격의 수수료','매입외환은 외국환은행이 고객으로부터 매입한 수출환어음, 내국신용장어음, 외화수표, 약속어음 등의 외국환으로 표시된 자산을 말한다. 외국환은행이 수출환어음 등의 외국환을 매입하면 원화 대금은 즉시 고객에게 지급되나 외화 자금은 추심 후 외국환은행에게입금된다. 따라서 원화 자금 지급일로부터 외화 자금 입금일까지 은행이 고객에게 자금을 대출해주는 효과가 발생한다. 이와 같이 외국환은행이 고객으로부터 수출환어음 등을 매입하는 경우, 고객에게 원화 대금을 지급한 시점과 어음 등의 발행자로부터 외화자금을 받는 시점 사이에 은행이 부담하는 어음금액에 대한 이자와 환차손 등을 보전받기 위해고객에게 수수료를 부과하는데 이를 환가료라고 한다. 따라서 환가료가 징수되는 거래는 은행이 고객으로부터 어음 등을 매입한 후 그 대금을 외화자금으로 수취하는 거래이다. 만약 원화로 대금을 수취할 경우에는 원/달러 환율 등이 적용되고 이 환율에 수수료가 포함되기 때문에 환가료를 따로 징수하지 않는 것이 일반적이다.','','ㅎㄱㄹ',ARRAY['내국신용장','매입외환']::text[]),
(731,'실질국내총생산','기준연도 가격으로 계산해 물가 변동을 뺀 국내총생산','명목국내총생산(Nominal GDP)은 한 나라 안에서 생산된 최종생산물의 가치를 그 생산물이 생산된 기간의 가격을 적용하여 계산한 것이다. 명목GDP의 변동분에는 최종생산물의 수량과 가격변동분이 혼재되어 있다. 명목GDP는 경제규모 등의 파악에 이용된다. 반면 실질국내총생산(Real GDP)은 한 나라 안에서 생산된 최종생산물의 가치를 기준년도 의 가격으로 측정한 것이다. 실질GDP는 우리나라를 비롯한 많은 국가에서 UN이 권고한 국제기준인 국민계정체계(SNA; System of National Accounts)에 따라 연쇄가중법에 의 해 추계되고 있다. 연쇄가중법은 기준연도의 가중치를 계속 적용하지 않고 기준연도의 명목금액에 연쇄물량지수를 곱하여 실질GDP를 산출한다. 실질GDP는 경제성장, 경기변동등 전반적인 경제활동의 흐름을 분석하는 데 이용된다. 명목GDP는 특정 시점의 국가간비교, 다른 지표의 기준치(예: 총저축률, GDP대비 경상수지 비율 등)로 활용된다.','','ㅅㅈㄱㄴㅊㅅㅅ',ARRAY['연쇄가중법','계절변동조정시계열','경제성장률','명목국내총생산']::text[]),
(732,'실질금리','명목금리에서 물가상승률을 뺀, 실제 돈의 가치로 본 금리','금리는 돈의 가치 즉, 물가변동을 고려하느냐의 여부를 기준으로 명목금리와 실질금리로 구분할 수 있다. 명목금리는 돈의 가치 변동을 고려하지 않고 외부로 표현된 표면상의 금리를 말한다. 이와 달리 실질금리는 물가상승률을 고려한 금리를 의미한다. 예컨대 금년중 1년 만기 정기예금의 명목금리가 3%이고 물가상승률이 1%일 경우 명목금리는 3%이 지만 실질금리는 2%(=3%-1%)가 된다. 한편, 금리와 물가의 관계를 설명하는 피셔효과 (Fisher effect)란 금융거래시 명목금리는 실질금리에 예상 물가상승률을 더해서 결정되는 것을 말한다. 예를 들어 시장참가자들이 미래의 인플레이션율을 합리적으로 예상하여실질금리에 덧붙이는 형태로 금리를 결정한다면 실질금리는 변하지 않고 명목금리만 조정될 수 있는 것이다. 그러나 경험적으로 1970~80년대 두 자릿수의 인플레이션 시대에 명목금리에서 물가상승률을 차감한 사후적(ex post) 실질금리가 마이너스로 나타나는 사례도 있어 장기적으로 실질금리가 불변한다는 견해에 대해서는 논란이 있다.','','ㅅㅈㄱㄹ',ARRAY['피셔효과','명목금리']::text[]),
(733,'실질소득','물가 변동을 반영해 실제 구매력 기준으로 본 소득','명목소득(Nominal Income)은 대상 경제주체의 소득이 발생할 당시의 가격으로 측정된 소득을 말하며, 실질소득(Real Income)은 통화가치의 변동을 감안하여 명목소득을 기준시점에 맞춰 조정한 것을 말한다. 예를 들어 2015년에 A씨의 연간 소득을 당시 통화가 치로 측정한 금액이 3,000만원 이라면 명목소득은 3,000만원에 해당한다. 2017년 측정된 A씨의 명목소득이 3,500만원이라면, 2년 동안 A씨의 명목소득은 500만원 증가한 셈이다. 이 경우 A씨의 경제형편이 나아졌는지를 판단하기 위해서는 보다 정확한 정보를 반영하고 있는 실질소득의 변화 여부를 확인해 보아야 한다. 만약 2015~2017년중 인플레이션율(물가상승률)이 15%라면 같은 기간중 통화가치는 15% 하락한 것으로 볼 수 있다. 이 경우 A씨의 2017년 명목소득 3,500만원은 실질소득 기준으로 3,043만원(3500/ (1+0.15))이 된다. 따라서 2015~2017년중 통화가치 변동을 감안할 경우 A씨의 실질소득은 43만원 증가한 것이 된다. 통화의 가치는 인플레이션 등으로 인해 시간이 지날수록 하락하므로 수시로 발표되는 다양한 경제지표를 정확하게 이해하기 위해서는 명목 (nominal)과 실질(real)의 개념으로 구분해서 살펴보아야 한다. 국내총생산에 대한 명목 GDP·실질GDP, 임금에 대한 명목임금·실질임금, 이자율에 대한 명목이자율·실질이자율등은 명목지표와 실질지표를 구분하는 한 예라 하겠다.','','ㅅㅈㅅㄷ',ARRAY['실질임금','명목소득']::text[]),
(734,'유통정지화폐','법으로 쓸 수 없게 된 옛 화폐(한국은행에서 교환만 가능)','발행중지화폐는 발권기관인 한국은행이 화폐의 원활한 유통 등을 위해 발행을 중지하기로 한 화폐이다. 발행중지화폐는 비록 화폐 발행은 중단되지만 화폐로서의 강제통용력도 있고 지급결제수단으로 사용도 가능하다. 또한 발행중지화폐는 한국은행 및 금융기관에서 현행 사용하고 있는 화폐와 ‘액면가’로 교환할 수 있다. 이에 반해 유통정지화폐는 화폐 발행을 중단할 뿐만 아니라 시중에서의 사용도 정지된 화폐이다. 즉 화폐로서의 강제통용력이 상실되어 지급결제수단으로 사용할 수 없다. 현재 우리나라 화폐 중 1962 년 제2차 통화조치 이전에 발행된 화폐들은 화폐로서의 효력이 상실된 유통정지화폐이고 1962년 제2차 통화조치 이후에 발행된 화폐 중 현재 사용하고 있는 은행권 4종류(오만원권, 만원권, 오천원권, 천원권)와 주화 6종류(오백원화, 백원화, 오십원화, 십원화, 오원화, 일원화)를 제외한 모든 화폐는 발행중지화폐이다.','','ㅇㅌㅈㅈㅎㅍ',ARRAY['제1차 통화조치','제2차 통화조치','발행중지화폐']::text[]),
(735,'무권화','실물 증권 자체를 없애고 전자 등록으로만 권리를 관리하는 것','증권의 부동화(Immobilization)란 실물증권을 중앙예탁기관에 집중 보관하여 매매거래 또는 담보거래 등에 따른 증권의 권리이전을 계좌대체 방식으로 처리함으로써 증권의 실물인도의 필요성을 제거하는 것을 말한다. 증권실물은 이동하지 않고 예탁기관의 장부상 대차기재에 의하여 증권에 대한 권리가 이전됨으로써 실물증권 이동에 따른 분실· 도난의 위험성, 사무처리의 번잡성 등의 문제점을 해결할 수 있다. 한편 증권의 무권화(Dematerialization)란 유가증권에 대한 권리를 표시하는 실물증권을 발행하지 않고 증권에 대한 권리가 오로지 장부(발행기관 및 중앙예탁기관의 계좌)상에 전자기록 형태로 존재하도록 하여 신주발행 및 증권유통에 따른 권리를 이전하는 것을 말한다.','','ㅁㄱㅎ',ARRAY['중앙예탁기관','부동화']::text[]),
(736,'하드랜딩','고성장 경기가 갑자기 침체로 곤두박질치는 경착륙','소프트랜딩(연착륙)은 높은 성장세를 보이는 호황기 경제가 큰 충격 없이 점진적으로 둔화되어 안정되는 것을 말한다. 반대로 하드랜딩(경착륙)은 갑작스러운 정책 변경이나 외부 충격으로 고성장 경제가 급격하게 침체 상태로 빠지는 것을 의미한다. 경기 순환과 통화정책 운용의 평가 과정에서 경기 흐름을 설명하기 위해 주로 사용되고 있다. 또한 높은 인플레이션 상황에서 급격한 경기침체나 실업 증가를 야기하지 않으면서 성장률을 낮추기 위한 정책 운용과 연관된 단어이다. 원래 비행기의 착륙이나 우주선의 궤도 진입 기법과 관련된 용어로 경제학자들이 비유적으로 사용하기 시작하였다. 소프트랜딩은 미국경제가 호황이던 1980년대 연방준비제도이사회(Board of Governors of the Federal Reserve System)가 성장세를 크게 해치지 않으면서 인플레이션 상황을 타개하기 위한 금리 인상을 설명하면서 역사적으로 처음 사용되었다. 호황과 불황이 순환하는 자본주의 경제가 호황국면에서 적절한 정책 운용을 통해 투자심리 위축, 실질소득 감소로 인한 소비부진 등의 부작용을 최소화하는 상황과 관련된다.','','ㅎㄷㄹㄷ',ARRAY['경기','최종수요','중간수요','소프트랜딩']::text[]),
(737,'명목화폐','그 자체는 가치가 없지만 국가가 보증해 돈으로 통하는 지폐·동전','고유의 사용가치 및 교환가치를 가지고 화폐의 기능을 수행하는 물건을 실물화폐라고 한다. 화폐경제 초기에는 각기 그 사회의 고유한 사정에 의해 생산량이나 존재량이 충분하지못하여 희소가치가 있는 조개 등 귀한 물건 또는 교환의 도구로 사용하기에 적당한 가축, 면포 등이 실물화폐로 사용되었으나 점차 운반도 간편하고 변질도 되지 않는 내구성이 있는 귀금속, 특히 금 또는 은이 주로 실물화폐로 쓰여졌다. 이러한 실물화폐는 경제규모가 커짐에 따라 필요한 양만큼 보관과 운반이 불편하여 소재가치와 교환가치가 다른 무엇을 화폐로 사용하게 되는데 이를 명목화폐라고 한다. 오늘날에는 은행권(지폐)으로 대표되는 명목화폐가 화폐의 대부분을 이룬다. 명목화폐는 그 자체가 가치를 가져서 화폐가 된 것이 아니라, 법률에 근거하거나 역사적인 관습이 그대로 사회적 신임을 얻어 통용되게 된 것이다.','','ㅁㅁㅎㅍ',ARRAY['실물화폐']::text[]),
(738,'연방준비은행(FRB)','미국 12개 지역에 있는 연준 산하 지역 중앙은행','연방준비제도(FRS; Federal Reserve System)는 1907년 금융공황 후 그 대책으로서 1913년에 제정된 연방준비법(Federal Reserve Act)에 의해서 창설된 미국 특유의 중앙은행제도이다. 동 제도는 연방준비제도이사회(Board of Governors)와 연방공개시장위원회(Federal Open Market Committee)를 정점으로 이들을 지원하는 본부와 12개 지역 연방준비은행(FRB; Federal Reserve Bank)으로 구성되어 있다. 연방준비제도이사회는 상원의 승인을 얻어 대통령이 임명하는 7인의 전임이사로 구성되며, 통화정책을 수립하고 지역 연방준비은행을 통할하는 최고 의사결정기구이다. 연방공개시장위원회는 공개시장운영정책을 수립·집행하는 기구이며, 연방준비은행에 대해서 지정한 공개시장운영의 실시를 명할 수 있다. 한편, 지역 연방준비은행은 12개 지역의 중앙은행 역할을 하며, 금융기관 지급준비금관리, 재할인, 지급결제, 연방준비권의 발행, 가맹 주립은행에 대한 업무감독, 국고대리업무 등 연방준비제도의 일상적인 업무를 수행한다.','','ㅇㅂㅈㅂㅇㅎ',ARRAY['중앙은행','연방준비제도(FRS)']::text[]),
(739,'위험가중치','자산의 위험도에 따라 정해진 비율(국채 0%, 기업대출 100% 등)','자기자본비율 산출시 대차대조표상 자산계정의 단순 합계를 분모로 사용할 경우 자산을 구성하는 각 익스포저에 따른 리스크를 반영할 수 없는 문제가 있다. 그러므로 각 익스포저 금액에 해당 위험가중치를 곱하여 합산한 금액인 위험가중자산을 분모로 사용하게 된다. 위험가중자산은 신용·시장·운영리스크로 구성된다. 각 리스크별 위험가중자산을 산출하는 방식은 바젤은행감독위원회(BCBS)가 제시한 방법을 따르는 표준방법과 은행의 자체 내부모형을 이용하는 방법으로 구분할 수 있다. 예를 들어 신용리스크 표준방법을 사용할 경우 익스포저에 거래상대방별 위험가중치를 곱한 금액을 합산하여 위험가중자산을 산출한다. 내부 모형을 사용하는 은행의 경우 자체 추정한 차주 부도율, 부도시 손실률, 부도시 익스포저 등을 사용하여 위험가중자산을 산출한다.','','ㅇㅎㄱㅈㅊ',ARRAY['BIS 자기자본비율','익스포저','내부등급법','위험가중자산']::text[]),
(740,'비정규직','계약직·시간제·파견처럼 기간이나 형태가 제한된 고용','정규직은 법적인 개념은 아니지만 기간이 정해져 있지 않은 고용형태로 근로자와 사업주가 직접 근로계약을 체결하고 전일제로 근무하면서 정년까지 보장된다는 의미로 받아들이고 있다. 따라서 회사가 소멸되지 않는 한 원할 때까지 계속 근무가 가능하며 임금, 휴가, 상여금 등의 각종 복지혜택도 받을 수 있다. 반면 비정규직은 근로기간이 정해져 있는 계약직과 일용직, 파견 도급직, 상시 근로를 하지 않는 시간제 근로자 등을 포함하는 개념으로 계약기간이 종료되는 시점이 정해져 있다. 인턴은 일정기간 근무시켜 능력과 성품등을 평가하여 필요시 채용하는 방식이다. 계약직은 일반계약직과 무기계약직으로 구분할 수 있다. 우선 일반계약직은 회사와 근로자가 정해진 한정된 기간에 근로계약을 맺은 것으로 정년이 보장되지 않기 때문에 정규직보다 불안정하고 임금 및 근무환경이 열악하다. 무기계약직은 일반계약직과는 달리 계약기간을 정하지 않은 것이지만 임금 및 복지나 승진 등에 대해서는 일반계약직과 비슷하다. 파견직은 아웃소싱 업체에 고용되어 있으면서 다른 업체로 파견되어 일하는 근로자를 말한다. 파견기간이 2년이 넘게 되면 파견 나 간 다른 업체에서 직접 고용해야 할 의무가 생긴다.','','ㅂㅈㄱㅈ',ARRAY['한시적 근로자','정규직']::text[]),
(741,'제조업가동률지수','생산능력 대비 실제 생산 비율(설비 이용도)을 나타낸 지수','생산능력지수는 공급능력의 수준과 동향이 어떻게 변화하는가를 나타낸 것이며, 가동률지수는 생산실적과 생산능력의 비율인 설비이용도를 지수화한 것으로서 경기동향 분석의 기초 자료로 이용된다. 두 지수는 공급능력과 설비가동의 절대수준을 나타내는 것이 아니라 기준년도의 생산능력과 가동률을 100으로 하였을 때 비교시의 공급능력과 가동상태가 어느 수준인가를 나타낸다. 일반적으로 생산은 자가소비, 출하 및 재고변동의 합으로 표현하는데 출하가 생산보다 경기에 대해 민감(선행)한 경향이 있다. 따라서 경기가 하강하는 경우 출하는 즉시 감소하나 기업이 생산을 급격히 감소시키기 어려우므로 재고가 증가 하게 된다. 반대로 경기가 회복되는 경우 출하가 증가하면서 재고가 감소하고 뒤따라 생산이 증가하게 된다. 한편, 가동률은 경기의 움직임에 따라 변동한다. 가동률 = 생산실적/생산능력×100','','ㅈㅈㅇㄱㄷㄹㅈㅅ',ARRAY['제조업평균가동률갭','제조업생산능력지수']::text[]),
(742,'융통어음','상거래 없이 단순히 자금을 융통하려고 발행하는 어음','진성어음(Commercial Bill)이란 기업간 상거래에 있어 대금결제를 위해 발행되는 어음 으로 상업어음, 물품대금어음(물대어음)이라고도 한다. 진성어음을 받은 납품업체는 약정된 날짜에 현금을 받을 수 있으나 원활한 자금순환을 위해 금융기관에서 미리 할인받아 현금화하는 것이 일반적이다. 진성어음은 상거래를 수반할 때만 발행할 수 있다는 점에서 순수하게 자금을 조달할 목적으로 발행되는 융통어음(Accommodation Bill)과는 구별된다. 진성어음과 융통어음은 모두 약속어음의 일종으로 외견상 구분할 수 있는 기준은 없다. 다만 금융기관은 진성어음을 할인하는 과정에서 어음 뒷면에 납품기업의 세금계산서를 첨부하도록 요구해 진성어음임을 확인한다. 융통어음 중에서도 신용상태가 양호한 기업이 운전자금 등 단기자금을 조달하기 위해 자기신용(대부분 신용평가기관의 신용평가 필요)을 바탕으로 발행하여 단기금융시장에서 유통되는 어음을 기업어음(CP; Commercial Paper)이라고 한다.','','ㅇㅌㅇㅇ',ARRAY['기업어음(CP)','진성어음']::text[]),
(743,'평균소비성향','처분가능소득 중 소비로 쓴 비율','총저축은 국민총처분가능소득에서 소비하고 남은 부분이다. 총저축은 투자재원으로 차기생산을 증가시키는데 이용되거나 대외자산구입에 이용되므로 이론적으로는 국내총투자에 국외투자를 더한 총투자와 일치한다. 총저축 = 국민총처분가능소득 - 소비총저축률은 100에서 국민총처분가능소득 중 최종소비를 목적으로 처분된 재화와 서비스의 비율인 소비율을 차감한 것이다. 이때 소비율을 백분율이 아닌 계수로 표시한 것을 평균소비성향이라 하며, 평균저축성향은 1에서 평균소비성향을 차감한 것이다. 총저축률 = 100 - 소비율* * 최종소비지출/국민총처분가능소득** × 100 ** ‌피용자보수 + 영업이익(국외순수취영업이익 및 재산소득 포함) + 순생산 및 수입세 +국외순수취경상이전 + 고정자본소모)평균소비성향 = 최종소비지출/국민총처분가능소득평균저축성향 = 1 - 평균소비성향','','ㅍㄱㅅㅂㅅㅎ',ARRAY['국민총처분가능소득','국민계정체계(SNA)','총저축률','평균저축성향']::text[]),
(744,'평균저축성향','처분가능소득 중 저축한 비율','총저축은 국민총처분가능소득에서 소비하고 남은 부분이다. 총저축은 투자재원으로 차기생산을 증가시키는데 이용되거나 대외자산구입에 이용되므로 이론적으로는 국내총투자에 국외투자를 더한 총투자와 일치한다. 총저축 = 국민총처분가능소득 - 소비총저축률은 100에서 국민총처분가능소득 중 최종소비를 목적으로 처분된 재화와 서비스의 비율인 소비율을 차감한 것이다. 이때 소비율을 백분율이 아닌 계수로 표시한 것을 평균소비성향이라 하며, 평균저축성향은 1에서 평균소비성향을 차감한 것이다. 총저축률 = 100 - 소비율* * 최종소비지출/국민총처분가능소득** × 100 ** ‌피용자보수 + 영업이익(국외순수취영업이익 및 재산소득 포함) + 순생산 및 수입세 +국외순수취경상이전 + 고정자본소모)평균소비성향 = 최종소비지출/국민총처분가능소득평균저축성향 = 1 - 평균소비성향','','ㅍㄱㅈㅊㅅㅎ',ARRAY['국민총처분가능소득','국민계정체계(SNA)','총저축률','평균소비성향']::text[]),
(745,'중간수요','생산 과정에서 원재료로 쓰이는 재화와 서비스에 대한 수요','어떤 재화나 서비스를 구매하고자 하는 능력과 욕구를 수요라 하는데 이는 용도에 따라중간수요와 최종수요로 나눌 수 있다. 최종수요는 가계나 일반정부의 소비 혹은 기업의 자본 형성 등과 같이 최종적인 목적으로 사용되는 재화나 서비스를 가리킨다. 이는 생산과정에서 원재료로 투입되는 재화나 서비스를 가리키는 중간수요의 상대개념이다. 예를 들면 밀가루가 가정에 판매되었을 때 밀가루에 대한 수요는 최종수요가 되지만 제빵공장에 빵의 원료로 판매되었을 때에는 중간수요가 된다.','','ㅈㄱㅅㅇ',ARRAY['중간소비','최종수요']::text[]),
(746,'말잔','월말·분기말 등 기간 마지막 날의 잔액','평잔과 말잔은 금융기관의 업무에서 자주 사용되는 용어로, 각각 평균잔액(average balance)과 기말잔액(end-of period balance)의 줄임말이다. 평잔(평균잔액)은 일정 기간의 일일 잔액을 합산한 후 해당 기간의 일수로 나눈 값으로 평균치를 의미한다. 예를 들어 3월 1일부터 3월 31일까지의 1개월 평잔은 각 날짜의 잔액을 합산한 후 31로 나눈 값이다. 은행 등은 이자 계산이나 수익 평가시 평잔을 주로 사용한다. 반면 말잔(기말잔액) 은 일정 기간의 말일 시점에서 측정된 잔액이다. 예를 들어 6월말이나 12월말의 잔액을 가리킨다. 은행 등은 결산이나 특정 시점의 잔액을 표시할 때 사용한다. 금융기관의 작성편의상 말잔이 용이함에도 평잔을 편제하는 이유는 기간 말일이 되면 경제주체의 자금 운용 행태가 크게 달라질 가능성이 있기 때문이다. 예를 들어 기업들은 분기말에 재무비율개선을 위해 자금을 상환하였다가 다음 분기 초에 다시 대출을 받는 행태를 보인다. 이러한 행태로 인해 분기말에 일시적으로 잔액이 감소할 수 있기 때문에 평잔을 관측할 필요가 있다.','','ㅁㅈ',ARRAY['평잔']::text[]),
(747,'환차익','환율 변동으로 외화 자산·부채를 원화로 환산할 때 생긴 이익','환위험은 크게 회계적 환위험(또는 환산환위험)과 거래적 환위험으로 나누는데, 이중에 서도 회계적 환위험이란 해외지사 및 자회사의 재무제표를 모기업의 재무제표와 연결시키기 위해 자산과 부채의 가치를 동일한 통화로 환산하는 과정에서 발생하는 환위험을 말한다. 환차손/환차익은 회계적 환위험과 관련되는 것으로, 한 경제주체가 외화 자산 또는 부채를 보유하고 있을 때 환율변동에 따라 자국 통화로 평가한 자산(부채)의 가치가 변동하게 되는데, 환율 변동에 따라 이익이 발생하면 환차익이라고 하고 반대로 손실이 발생하면 환차손이라고 한다. 예를 들어 외화자산이 외화부채보다 많은 경우(외환매입초과 포지션, over-bought positions 또는 long positions) 환율이 상승(하락)하면 환차익(손) 이 발생하고 반대로 외화부채가 외화자산보다 많은 경우(외환매도초과포지션, over-sold positions 또는 short positions) 환율이 상승(하락)하면 환차손(익)이 발생한다. 환차손이 발생할 위험을 관리하는 방법으로는 리드앤드래그, 매칭, 자산부채관리 등 기업 내부적으로 환위험을 최소화하는 내부적 관리기법과 은행과의 외환파생상품을 이용한 대응거래 등을 통해 환위험을 커버하는 외부적 관리기법이 있다.','','ㅎㅊㅇ',ARRAY['외국환포지션','환차손']::text[]);

-- 분리 자식에 부모 진도 복사: 패스가 코스 잠금을 words.every(known)으로 판정하므로 없으면 뒤 코스가 다시 잠긴다.
-- INSERT 트리거(미션 진행·XP 지급)가 타지 않게 잠시 끈다 (README 되돌리기와 동일).
ALTER TABLE public.word_progress DISABLE TRIGGER trg_word_progress_mission;
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 717, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 9 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 직접금융 <- 간접금융/직접금융
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 718, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 10 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 직접세 <- 간접세/직접세
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 719, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 21 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 전업주의 <- 겸업주의/전업주의
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 720, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 33 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 비경제활동인구 <- 경제활동인구/비경제활동인구/ 경제활동참가율
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 721, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 33 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 경제활동참가율 <- 경제활동인구/비경제활동인구/ 경제활동참가율
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 722, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 45 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 자유변동환율제도 <- 고정환율제도/자유변동환율제도
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 723, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 76 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 국민총처분가능소득(GNDI) <- 국민처분가능소득(NDI)/ 국민총처분가능소득(GNDI)
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 724, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 167 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 복리 <- 단리/복리
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 725, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 169 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 복수금리방식 <- 단일금리방식/복수금리방식
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 726, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 171 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 익일결제 <- 당일결제/익일결제/익익일결제
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 727, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 171 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 익익일결제 <- 당일결제/익일결제/익익일결제
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 728, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 190 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 커플링 <- 디커플링/커플링
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 729, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 199 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 리스크 오프(Risk Off) <- 리스크 온(Risk On)/오프(Off)
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 730, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 206 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 환가료 <- 매입외환/환가료
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 731, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 210 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 실질국내총생산 <- 명목국내총생산/실질국내총생산
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 732, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 211 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 실질금리 <- 명목금리/실질금리
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 733, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 212 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 실질소득 <- 명목소득/실질소득
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 734, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 229 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 유통정지화폐 <- 발행중지화폐/유통정지화폐
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 735, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 252 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 무권화 <- 부동화/무권화
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 736, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 313 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 하드랜딩 <- 소프트랜딩/하드랜딩
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 737, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 360 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 명목화폐 <- 실물화폐/명목화폐
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 738, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 383 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 연방준비은행(FRB) <- 연방준비제도(FRS)/ 연방준비은행(FRB)
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 739, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 425 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 위험가중치 <- 위험가중자산/위험가중치
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 740, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 508 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 비정규직 <- 정규직/비정규직
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 741, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 517 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 제조업가동률지수 <- 제조업생산능력/가동률지수
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 742, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 563 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 융통어음 <- 진성어음/융통어음
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 743, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 582 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 평균소비성향 <- 총저축/총저축률/평균소비성향/ 평균저축성향
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 744, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 582 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 평균저축성향 <- 총저축/총저축률/평균소비성향/ 평균저축성향
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 745, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 585 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 중간수요 <- 최종수요/중간수요
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 746, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 630 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 말잔 <- 평잔/말잔
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 747, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 672 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 환차익 <- 환차손/환차익
ALTER TABLE public.word_progress ENABLE TRIGGER trg_word_progress_mission;
