-- ===== 분리 자식 진도 복사 잔여분 (16_words_refine_1.sql 뒷부분만 다시) =====
-- ON CONFLICT로 이미 복사된 행은 건너뛰므로 다시 실행해도 안전하다. 마지막 줄의 트리거 재활성화가 핵심.

-- 분리 자식에 부모 진도 복사: 패스가 코스 잠금을 words.every(known)으로 판정하므로 없으면 뒤 코스가 다시 잠긴다.
-- INSERT 트리거(미션 진행·XP 지급)가 타지 않게 잠시 끈다 (README 되돌리기와 동일).
ALTER TABLE public.word_progress DISABLE TRIGGER trg_word_progress_mission;
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 717, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 9 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 직접금융 <- 간접금융/직접금융
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 718, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 10 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 직접세 <- 간접세/직접세
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 719, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 21 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 전업주의 <- 겸업주의/전업주의
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 720, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 33 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 비경제활동인구 <- 경제활동인구/비경제활동인구/ 경제활동참가율
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 721, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 33 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 경제활동참가율 <- 경제활동인구/비경제활동인구/ 경제활동참가율
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 722, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 45 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 자유변동환율제도 <- 고정환율제도/자유변동환율제도
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 723, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 76 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 국민총처분가능소득(GNDI) <- 국민처분가능소득(NDI)/ 국민총처분가능소득(GNDI)
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 724, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 167 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 복리 <- 단리/복리
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 725, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 169 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 복수금리방식 <- 단일금리방식/복수금리방식
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 726, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 171 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 익일결제 <- 당일결제/익일결제/익익일결제
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 727, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 171 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 익익일결제 <- 당일결제/익일결제/익익일결제
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 728, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 190 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 커플링 <- 디커플링/커플링
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 729, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 199 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 리스크 오프(Risk Off) <- 리스크 온(Risk On)/오프(Off)
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 730, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 206 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 환가료 <- 매입외환/환가료
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 731, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 210 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 실질국내총생산 <- 명목국내총생산/실질국내총생산
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 732, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 211 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 실질금리 <- 명목금리/실질금리
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 733, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 212 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 실질소득 <- 명목소득/실질소득
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 734, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 229 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 유통정지화폐 <- 발행중지화폐/유통정지화폐
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 735, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 252 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 무권화 <- 부동화/무권화
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 736, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 313 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 하드랜딩 <- 소프트랜딩/하드랜딩
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 737, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 360 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 명목화폐 <- 실물화폐/명목화폐
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 738, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 383 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 연방준비은행(FRB) <- 연방준비제도(FRS)/ 연방준비은행(FRB)
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 739, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 425 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 위험가중치 <- 위험가중자산/위험가중치
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 740, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 508 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 비정규직 <- 정규직/비정규직
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 741, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 517 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 제조업가동률지수 <- 제조업생산능력/가동률지수
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 742, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 563 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 융통어음 <- 진성어음/융통어음
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 743, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 582 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 평균소비성향 <- 총저축/총저축률/평균소비성향/ 평균저축성향
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 744, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 582 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 평균저축성향 <- 총저축/총저축률/평균소비성향/ 평균저축성향
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 745, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 585 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 중간수요 <- 최종수요/중간수요
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 746, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 630 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 말잔 <- 평잔/말잔
INSERT INTO public.word_progress (user_id, word_id, status, ease, interval_d, reps, due_date, last_grade) SELECT user_id, 747, status, ease, interval_d, reps, due_date, last_grade FROM public.word_progress WHERE word_id = 672 ON CONFLICT (user_id, word_id) DO NOTHING;  -- 환차익 <- 환차손/환차익
ALTER TABLE public.word_progress ENABLE TRIGGER trg_word_progress_mission;

-- 확인:
-- SELECT tgname, tgenabled FROM pg_trigger WHERE tgrelid = 'public.word_progress'::regclass;  -- 모두 'O'
